apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubenodejs
  name: kubenodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubenodejs
  template:
    metadata:
      labels:
        app: kubenodejs
    spec:
      containers:
      - image: $DOCKER_IMAGE_NAME
        name: kubenodejs
---
apiVersion: v1
kind: Service
metadata:
  name: kubenodejs
  namespace: default
spec:
  ports:
  - nodePort: 31090
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: kubenodejs
  type: NodePort
